# -*- coding: utf-8 -*-
"""got.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cXXgCcl6PUaud8UWc3Nv1B_7KcnxFRQ
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

battle = pd.read_csv('battles.csv')
battle.head()

battle.shape

battle.rename(columns={'attacker_1':'primary_attacker'},inplace=True)
battle.head()

battle.rename(columns={'defender_1':'primary_defender'},inplace=True)
battle.head()

battle['attacker_king'].value_counts()   #no. of times a king has attacked

battle['location'].value_counts()   #no. of attacks in locations

sns.set(rc={'figure.figsize':(13,5)})   #bargraph using seaborn for a king and his army
sns.barplot(x='attacker_king',y='attacker_size',data=battle)
plt.show()

sns.set(rc={'figure.figsize':(13,5)})    #bargraph for a defender and his army
sns.barplot(x='defender_king',y='defender_size',data=battle)
plt.show()

sns.countplot(x=battle['attacker_king'],hue=battle['battle_type'])
plt.show()

death = pd.read_csv('character-deaths.csv')
death.head()

death.shape

death['Gender'].value_counts()

death['Nobility'].value_counts()

sns.countplot(x = death['Death Year'])
plt.show()

sns.set(rc={'figure.figsize': (50,20)})
sns.countplot(x = death['Allegiances'])
plt.show()

# Create count plot with rotated x-axis labels
sns.countplot(x=death['Allegiances'], order=death['Allegiances'].value_counts().index)
plt.xticks(rotation=45, ha='right')  # Rotate labels for better visibility
plt.show()

